#!/bin/sh

echo "Start install the dotfiles"

# backup the git files
cp ~/.gitconfig ~/.gitconfig.backup
cp ~/.gitconfig_local ~/.gitconfig_local.backup
cp ~/.gitignore ~/.gitignore.backup

# make the git files
rm ~/.gitignore && cp `pwd`/gitfiles/gitignore ~/.gitignore
rm ~/.gitconfig && cp `pwd`/gitfiles/gitconfig ~/.gitconfig
rm ~/.gitconfig_local && `pwd`/gitfiles/gitconfig_local ~/.gitconfig_local

# include alias.zsh
echo "source `pwd`/zsh/alias" >> ~/.zshrc

echo "Installation is completed"
