#!/bin/sh

function cecho { echo -e "\e[34m$*\e[m"; }

echo "(*'-') < Start install the dotfiles"

###
# Vim Setup
###

cecho "Starting Vim setup"

# backup the vim files
if [ -e ~/.vimrc ]; then
  cp ~/.vimrc ~/.vimrc.backup
fi

# make the vim files
cp `pwd`/vim/vimrc ~/.vimrc

###
# Git Setup
###

cecho "Starting Git setup"

# backup the git files
if [ -e ~/.gitconfig ]; then
  cp ~/.gitconfig ~/.gitconfig.backup
fi
if [ -e ~/.gitconfig_local ]; then
  cp ~/.gitconfig_local ~/.gitconfig_local.backup
fi
if [ -e ~/.gitignore ]; then
  cp ~/.gitignore ~/.gitignore.backup
fi

# make the git files
cp `pwd`/gitfiles/gitignore ~/.gitignore
cp `pwd`/gitfiles/gitconfig ~/.gitconfig

# make original gitconfig_local file
GIT_NAME=""
GIT_MAIL=""
cecho "Please enter your GitHub name"
read GIT_NAME
cecho "Please enter your GitHub e-mail address"
read GIT_MAIL

cp `pwd`/gitfiles/gitconfig_local ~/.gitconfig_local
  sed -i s/{git_user_name}/${GIT_NAME}/g    ~/.gitconfig_local | \
  sed -i s/{git_email_address}/${GIT_MAIL}/g ~/.gitconfig_local

###
# Zsh Setup
###

# include alias.zsh
cecho "Starting zsh setup"

# backup the zsh files
if [ -e ~/.zshrc ]; then
  cp ~/.zshrc  ~/.zshrc.backup
fi
if [ -e ~/.zshenv ]; then
  cp ~/.zshenv ~/.zshenv.backup
fi

# cp zsh files
cp `pwd`/zsh/zshrc.zsh ~/.zshrc
cp `pwd`/zsh/zshenv.zsh ~/.zshenv

###
# tmux Setup
###

cecho "Startging tmux setup"

# backup .tmux.conf
if [ -e ~/.tmux.conf ]; then
  cp ~/.tmux.conf ~/.tmux.conf.backup
fi

# cp tmux.conf
cp `pwd`/tmux/tmux.conf ~/.tmux.conf

cecho "Installation is completed"
